version: "3.7"

services:
  # Je veux un conteneur qui s'appelle "mongo" et qui utilise l'image "mongo"
  mongo:
    image: mongo # Nom de l'image à utiliser
    ports: # Ports à ouvrir
      - "27017:27017" # Je connecte le port 27017 en local au port 27017 de mongoDb
  mongo-express: # Un ui pour mongo
    image: mongo-express
    ports:
      - "8081:8081"